galaxy_info:
  author: baztian
  role_name: dev_tools
  description: Role for installing various tools related to development tasks
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
  - name: Debian
    versions:
    - buster
  galaxy_tags:
    - development
    - dev
dependencies: []
