galaxy_info:
  author: baztian
  role_name: python
  description: Role for installing Python and associated tools
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
  galaxy_tags:
    - python
dependencies: []
