---
- hosts: all
  become: yes
  tasks:
    - name: Download required roles
      delegate_to: localhost
      command: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml
      become: no
      changed_when: False
      tags: always
    - block:
      - include_role: name=baztian.apt_upgrade
      tags: apt_upgrade
# ich nutze cinnamon,      
#    - block:
#      - include_role: name=baztian.xfce
#      tags: xfce
    - block:
      - include_role: name=baztian.git
      tags: git
    - block:
      - include_role: name=baztian.python
      tags: python
# hier muss ein interpreter gesetzt werden und python3-apt installiert werden
# sonst bricht ab wg fehlende abhaengigkeit
    - block:
      - include_role: name=baztian.asdf
      tags: asdf
# was soll das? warum nicht einfach den verfuegbaren emacs einfach installieren und gut?
#    - block:
#      - include_role: name=baztian.emacs
#      tags: emacs
# nein, ich möchte KeePassXC nehmen wg OTP
#    - block:
#      - include_role: name=baztian.keepass
#      tags: keepass
# gocryptfs auch sehr kompliziert, das gibt es doch auch normal zu laden
#    - block:
#      - include_role: name=baztian.gocryptfs
#      tags: gocryptfs
    - block:
      - include_role: name=docker
      tags: docker
    - block:
      - include_role: name=baztian.java
      tags: java
# brauche ich nicht
#    - block:
#      - include_role: name=baztian.jython
#      tags: jython
    - block:
      - include_role: name=baztian.vscode
      tags: vscode
    - block:
      - include_role: name=baztian.jetbrains_toolbox
      tags: jetbrains_toolbox
    - block:
      - include_role: name=baztian.js
      tags: js
    - block:
      - include_role: name=baztian.dev_tools
      tags: dev_tools
    - block:
      - include_role: name=baztian.aws
      tags: aws
    - block:
      - include_role: name=baztian.other_installs
      tags: other_installs
#    - block:
#      - include_role: name=baztian.multimedia
#      tags: multimedia
#    - block:
#      - include_role: name=baztian.squeezeplay
#      tags: squeezeplay
#    - block:
#      - include_role: name=baztian.skype
#      tags: skype
#    - block:
#      - include_role: name=baztian.calibre
#      tags: calibre
    - block:
      - include_role: name=vagrant
      tags: vagrant
#    - block:
#      - include_role: name=eac
#      tags: eac
    - block:
      - include_role: name=baztian.joplin
      tags: joplin
