- src: apt_upgrade
- src: git
- src: asdf
- src: vscode
- src: python
- src: pip_venv
- src: adr_tools
- src: dev_tools
- src: java
- src: aws
- src: keepass
- src: calibre
- src: joplin
- src: gocryptfs
- src: emacs
- src: jetbrains_toolbox
- src: js
- src: jython
- src: other_installs
- src: multimedia
- src: squeezeplay
- src: skype
- src: xfce
