galaxy_info:
  author: baztian
  role_name: emacs
  description: Role for installing emacs
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    - focal
  - name: Debian
    versions:
    - buster
  galaxy_tags:
    - emacs
dependencies: []
