galaxy_info:
  author: baztian
  role_name: skype
  description: Role for installing Skype
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
    - packages
    - apt
dependencies: []
