galaxy_info:
  author: baztian
  role_name: multimedia
  description: Role for installing various useful multimedia packages
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    - focal
  - name: Debian
    versions:
    - stretch
    - buster
  galaxy_tags:
    - packages
    - apt
dependencies: []
