galaxy_info:
  author: baztian
  role_name: other_installs
  description: Role for installing various useful packages via apt
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
  - name: Debian
    versions:
    - buster
  galaxy_tags:
    - packages
    - apt
dependencies: []
