galaxy_info:
  author: baztian
  role_name: adr_tools
  description: Role for installing ADR Tools
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    - focal
  - name: Debian
    versions:
    - stretch
    - buster
  galaxy_tags:
    - adr
    - architecture
dependencies: []
