---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- name: Determine whether Emacs 26 PPA required
  set_fact:
    ppa_required: "{{ ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
     or ansible_distribution == 'Ubuntu' and ansible_distribution_release in ('xenial', 'bionic')
     or ansible_distribution == 'Linux Mint' and ansible_distribution_major_version == '18' }}"
- name: Install dirmngr in order to be able to install the apt signing key
  apt:
    pkg:
      - dirmngr
  when: ppa_required
- name: Add PPA Key from Kevin Kelley
  apt_key:
    id: 873503A090750CDAEB0754D93FF0E01EEAAFC9CD
    keyserver: keyserver.ubuntu.com
  when: ppa_required
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP '{{ "VERSION" if ansible_distribution == "Debian" else "UBUNTU" }}_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
- name: Add Kevin Kelley's Emacs PPA (deb)
  apt_repository:
    repo: deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu {{ distro.stdout }} main
  when: ppa_required
- name: Add Kevin Kelley's Emacs PPA (deb-src)
  apt_repository:
    repo: deb-src http://ppa.launchpad.net/kelleyk/emacs/ubuntu {{ distro.stdout }} main
  when: ppa_required
- name: Install Emacs 26 without PPA
  apt:
    name:
    - emacs
    - emacs-el
  when: not ppa_required
- name: Install Emacs 26 from PPA
  apt:
    name:
    - emacs26
    - emacs26-el
  when: ppa_required
