---
#- name: Check if "official-package-repositories" list file exists
#  stat:
#    path: /etc/apt/sources.list.d/official-package-repositories.list
#  register: repos_list
#- name: Setup mirrors
#  replace:
#    path: /etc/apt/sources.list.d/official-package-repositories.list
#    regexp: "{{ item.regexp }}"
#    replace: "{{ item.replace }}"
#  with_items: "{{ official_apt_sources_replacements }}"
#  when: repos_list.stat.exists
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP '{{ "VERSION" if ansible_distribution == "Debian" else "UBUNTU" }}_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
#- name: Print distro name
#  ansible.builtin.debug:
#    msg: System {{ inventory_hostname }} use distro {{ distro }}
#- name: Print distro name
#  ansible.builtin.debug:
#    var: distro.stdout
- name: Update repos and upgrade all packages
  apt:
    update_cache: yes
    upgrade: safe
- name: Remove useless apt packages and dependencies
  apt:
    autoremove: yes
    autoclean: yes
