galaxy_info:
  author: baztian
  role_name: vscode
  description: Role for installing visual studio code
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
    - focal
  - name: Debian
    versions:
    - stretch
    - buster
  galaxy_tags:
    - visualstudio
    - vc
dependencies: []
