---
- name: Add key for shutter ppa
  become: yes
  apt_key:
    id: FC6D7D9D009ED615
    keyserver: keyserver.ubuntu.com

- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP '{{ "VERSION" if ansible_distribution == "Debian" else "UBUNTU" }}_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False

- name: Add Shutter PPA (deb)
  apt_repository:
    repo: deb http://ppa.launchpad.net/shutter/ppa/ubuntu {{ distro.stdout }} main

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Install shutter and related tools
  become: yes
  apt:
    pkg:
      - shutter
      - gnome-web-photo
      - gir1.2-appindicator3-0.1
