galaxy_info:
  author: baztian
  role_name: gocryptfs
  description: Role for installing gocryptfs
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
    - gocryptfs
dependencies: []
