---
- name: Check if ADR Tools {{ adr_tools_version }} already installed
  stat:
    path: /opt/adr-tools-{{ adr_tools_version }}/src/adr
  register: adr_bin
  tags: adr
- name: Download ADR Tools {{ adr_tools_version }}
  get_url:
    url: https://github.com/npryce/adr-tools/archive/refs/tags/{{ adr_tools_version }}.tar.gz
    checksum: "sha256:{{ adr_tools_sha256 }}"
    dest: /tmp
  when: not adr_bin.stat.exists
  tags: adr
- name: Unarchive ADR Tools {{ adr_tools_version }}
  unarchive:
    src: /tmp/adr-tools-{{ adr_tools_version }}.tar.gz
    dest: /opt
    remote_src: yes
  when: not adr_bin.stat.exists
  tags: adr
- name: Symlink default adr-tools
  file:
    src: "adr-tools-{{ adr_tools_version }}"
    dest: "/opt/adr-tools"
    state: link
  tags: adr
- name: Add adr executable script
  copy:
    src: adr
    dest: /usr/local/bin
    mode: 0755
  tags: adr
